"""Acceptance report (spec §40, Wave 10): every acceptance criterion with the tests that verify
it and how they ended in one pytest run.

Inputs: the spec (acceptance criteria), the tests' ``@pytest.mark.spec`` markers (as the
traceability checker reads them) and the JUnit XML that pytest wrote (``--junitxml``).
A criterion is

* ``PASS``     - at least one of its tests passed and none failed;
* ``FAIL``     - one of its tests failed or errored;
* ``SKIPPED``  - its tests ran but were all skipped on this machine (e.g. the MariaDB
  connector tests where no MariaDB is installed);
* ``NOT RUN``  - none of its tests is in the JUnit file;
* ``NO TEST``  - no test references it;
* ``DEFERRED`` - no test yet, with a recorded reason (``docs/acceptance_deferred.txt``).

Exit 1 when any criterion is FAIL, NOT RUN or NO TEST (SKIPPED is reported, not failed).

Usage:
    python tools/validators/acceptance_report.py --junit JUNIT.xml [--write REPORT.md]
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from traceability import (
    DEFAULT_DEFERRED,
    DEFAULT_SPEC,
    DEFAULT_TESTS,
    _sort_key,
    collect_references,
    load_deferred,
    parse_spec,
)

OUTCOMES = ("passed", "failed", "skipped")


def junit_outcomes(path: Path) -> dict[tuple[str, str], list[str]]:
    """(test module stem, test function or class name) -> outcomes of its runs."""
    out: dict[tuple[str, str], list[str]] = defaultdict(list)
    root = ET.parse(path).getroot()
    for case in root.iter("testcase"):
        module = case.get("classname", "").split(".")
        name = case.get("name", "").split("[", 1)[0]
        if case.find("failure") is not None or case.find("error") is not None:
            outcome = "failed"
        elif case.find("skipped") is not None:
            outcome = "skipped"
        else:
            outcome = "passed"
        # classname is "<path>.<module>" or "<path>.<module>.<Class>"
        for i in range(len(module)):
            if module[i].startswith("test_"):
                out[(module[i], name)].append(outcome)
                if i + 1 < len(module):  # a test method: also count it for its class
                    out[(module[i], module[i + 1])].append(outcome)
                break
    return out


def status(runs: list[str], has_tests: bool, deferred: bool = False) -> str:
    if not has_tests:
        return "DEFERRED" if deferred else "NO TEST"
    if not runs:
        return "NOT RUN"
    if "failed" in runs:
        return "FAIL"
    if "passed" in runs:
        return "PASS"
    return "SKIPPED"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--junit", type=Path, required=True)
    ap.add_argument("--write", type=Path, default=None)
    ap.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    ap.add_argument("--tests", type=Path, default=DEFAULT_TESTS)
    ap.add_argument("--label", default="", help="where the run happened (shown in the report)")
    args = ap.parse_args(argv)

    ids = parse_spec(args.spec)
    refs = [r for r in collect_references(args.tests) if r.spec_id in ids.acceptance]
    runs = junit_outcomes(args.junit)
    deferred = load_deferred(DEFAULT_DEFERRED)
    tests_of: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for r in refs:
        key = (r.file.stem, r.test)
        if key not in tests_of[r.spec_id]:
            tests_of[r.spec_id].append(key)

    rows = []
    counts: dict[str, int] = defaultdict(int)
    for at_id, text in sorted(ids.acceptance.items(), key=lambda kv: _sort_key(kv[0])):
        keys = tests_of.get(at_id, [])
        outcomes = [o for k in keys for o in runs.get(k, [])]
        st = status(outcomes, bool(keys), at_id in deferred)
        counts[st] += 1
        tally = ", ".join(f"{outcomes.count(o)} {o}" for o in OUTCOMES if outcomes.count(o))
        names = "<br>".join(f"`{m}::{t}`" for m, t in keys) or deferred.get(at_id, "")
        rows.append(f"| {at_id} | {text.replace('|', '/')} | {st} | {tally or '-'} | {names} |")

    summary = ", ".join(f"{n} {s}" for s, n in sorted(counts.items()))
    print(f"acceptance: {len(rows)} criteria - {summary}")
    if args.write:
        stamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            "# Acceptance report (spec §40)",
            "",
            "Generated by `tools/validators/acceptance_report.py` from one run of the test suite "
            "(`python tools/check.py --acceptance-report`). Do not edit by hand.",
            "",
            f"- Run: {stamp}{' - ' + args.label if args.label else ''}",
            f"- Result: {summary}",
            "",
            "| ID | Acceptance criterion | Status | Test runs | Tests |",
            "|---|---|---|---|---|",
            *rows,
        ]
        args.write.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"acceptance: report written to {args.write}")
    bad = counts["FAIL"] + counts["NOT RUN"] + counts["NO TEST"]
    print("acceptance: " + ("FAIL" if bad else "PASS"))
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
