"""Spec traceability checker.

Tests declare which part of docs/PHASE1_TECHNICAL_SPEC.md they verify with
``@pytest.mark.spec("AT-40.2.1", "D-01", "S-13")``.

ID forms (all derived from the spec text, never hard-coded here):

* ``AT-40.<sub>.<n>``  - n-th bullet under heading ``### 40.<sub>`` (acceptance baseline)
* ``D-0n``             - decision record heading ``### D-0n``
* ``G-n``              - design gate row ``| G-n ...`` in §0
* ``S-<n>`` / ``S-<n>.<m>`` - spec section headings ``## n.`` / ``### n.m``

The checker FAILS (exit 1) when a test references an ID that does not exist in the
spec (stale or mistyped traceability). Uncovered acceptance IDs are reported, and
only fail when ``--min-acceptance`` is set (Wave 10 uses 100).

Usage:
    python tools/validators/traceability.py [--min-acceptance PCT] [--write REPORT.md]
        [--spec PATH] [--tests PATH]
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SPEC = REPO_ROOT / "docs" / "PHASE1_TECHNICAL_SPEC.md"
DEFAULT_TESTS = REPO_ROOT / "backend" / "tests"
DEFAULT_DEFERRED = REPO_ROOT / "docs" / "acceptance_deferred.txt"

_AT_HEADING = re.compile(r"^###\s+40\.(\d+)\b")
_ANY_HEADING = re.compile(r"^#{1,6}\s")
_BULLET = re.compile(r"^- \S")
_DECISION = re.compile(r"^###\s+(D-\d{2})\b")
_GATE = re.compile(r"^\|\s*(G-\d+)\b")
_SECTION = re.compile(r"^#{2,3}\s+(\d+(?:\.\d+)?)\.?\s")


@dataclass
class SpecIds:
    acceptance: dict[str, str] = field(default_factory=dict)  # id -> bullet text
    decisions: set[str] = field(default_factory=set)
    gates: set[str] = field(default_factory=set)
    sections: set[str] = field(default_factory=set)

    def all(self) -> set[str]:
        return set(self.acceptance) | self.decisions | self.gates | self.sections


def parse_spec(path: Path) -> SpecIds:
    ids = SpecIds()
    current_at: str | None = None
    counter = 0
    in_code = False
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if line.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        if m := _DECISION.match(line):
            ids.decisions.add(m.group(1))
        if m := _GATE.match(line):
            ids.gates.add(m.group(1))
        if m := _SECTION.match(line):
            ids.sections.add("S-" + m.group(1))
        if m := _AT_HEADING.match(line):
            current_at, counter = f"40.{m.group(1)}", 0
            continue
        if _ANY_HEADING.match(line):
            current_at = None
            continue
        if current_at and _BULLET.match(line):
            counter += 1
            ids.acceptance[f"AT-{current_at}.{counter}"] = line[2:].strip()
    return ids


@dataclass(frozen=True)
class Reference:
    spec_id: str
    file: Path
    line: int
    test: str


def load_deferred(path: Path) -> dict[str, str]:
    """Acceptance IDs that cannot be tested yet -> reason (``AT-x | reason`` lines)."""
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        at_id, _, reason = (x.strip() for x in line.partition("|"))
        if not reason:
            raise SystemExit(f"traceability: {path.name}: {at_id} needs a reason")
        out[at_id] = reason
    return out


def collect_references(tests_root: Path) -> list[Reference]:
    refs: list[Reference] = []
    for path in sorted(tests_root.rglob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                continue
            for deco in node.decorator_list:
                if not isinstance(deco, ast.Call):
                    continue
                func = deco.func
                if isinstance(func, ast.Attribute) and func.attr == "spec":
                    for arg in deco.args:
                        if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                            refs.append(Reference(arg.value, path, deco.lineno, node.name))
    return refs


def render_report(
    ids: SpecIds, refs: list[Reference], deferred: dict[str, str] | None = None
) -> str:
    by_id: dict[str, list[Reference]] = {}
    for r in refs:
        by_id.setdefault(r.spec_id, []).append(r)
    lines = [
        "# Spec traceability report",
        "",
        "Generated by `tools/validators/traceability.py`. Do not edit by hand.",
        "",
        "## Acceptance baseline (spec §40)",
        "",
        "| ID | Acceptance criterion | Tests |",
        "|---|---|---|",
    ]
    for at_id, text in sorted(ids.acceptance.items(), key=lambda kv: _sort_key(kv[0])):
        n = len(by_id.get(at_id, []))
        shown = str(n) if n else ("deferred" if at_id in (deferred or {}) else "-")
        lines.append(f"| {at_id} | {text.replace('|', '/')} | {shown} |")
    lines += ["", "## Decisions", "", "| ID | Tests |", "|---|---|"]
    for d in sorted(ids.decisions):
        lines.append(f"| {d} | {len(by_id.get(d, [])) or '-'} |")
    return "\n".join(lines) + "\n"


def _sort_key(at_id: str) -> tuple[int, ...]:
    return tuple(int(x) for x in at_id[3:].split("."))


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    ap.add_argument("--tests", type=Path, default=DEFAULT_TESTS)
    ap.add_argument("--min-acceptance", type=float, default=None)
    ap.add_argument("--write", type=Path, default=None)
    ap.add_argument("--deferred", type=Path, default=DEFAULT_DEFERRED)
    args = ap.parse_args(argv)

    ids = parse_spec(args.spec)
    refs = collect_references(args.tests)
    deferred = load_deferred(args.deferred)
    known = ids.all()
    unknown = [r for r in refs if r.spec_id not in known]

    covered_at = {r.spec_id for r in refs if r.spec_id in ids.acceptance}
    covered_dec = {r.spec_id for r in refs if r.spec_id in ids.decisions}
    # Deferred criteria (with a recorded reason) are left out of the coverage figure.
    counted = set(ids.acceptance) - (set(deferred) - covered_at)
    total_at = len(counted)
    pct = 100.0 * len(covered_at & counted) / total_at if total_at else 0.0

    print(
        f"traceability: {len(refs)} reference(s); acceptance {len(covered_at & counted)}/"
        f"{total_at} ({pct:.1f}%), {len(ids.acceptance) - total_at} deferred; "
        f"decisions {len(covered_dec)}/{len(ids.decisions)}"
    )
    for at_id in sorted(set(deferred) - set(ids.acceptance)):
        unknown.append(Reference(at_id, args.deferred, 0, "(deferred list)"))
    for at_id in sorted(set(deferred) & covered_at):
        print(f"traceability: note - {at_id} is covered now; remove it from {args.deferred.name}")
    if args.write:
        args.write.write_text(render_report(ids, refs, deferred), encoding="utf-8")
        print(f"traceability: report written to {args.write}")

    failed = False
    if unknown:
        failed = True
        print(f"traceability: FAIL - {len(unknown)} reference(s) to IDs not in the spec:")
        for r in unknown:
            print(f"  {r.file.name}:{r.line} {r.test} -> {r.spec_id!r}")
    if args.min_acceptance is not None and pct < args.min_acceptance:
        failed = True
        print(f"traceability: FAIL - acceptance coverage {pct:.1f}% < {args.min_acceptance}%")
    if not failed:
        print("traceability: PASS")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
