"""Wave 1B foundation: HOSxP mirrors, plan_year, identity/RBAC, HoP appointment,
append-only audit_log, sync log.

Revision ID: 0001
Revises:
Create Date: 2026-09-28
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ROLES = [
    ("REQUESTER", "Requesting department staff"),
    ("PLAN_OFFICER", "Planning Group / Plan Officer"),
    ("PROCUREMENT", "Procurement staff"),
    ("HEAD_OF_PROCUREMENT", "Head of Procurement (requires a current appointment)"),
    ("FINANCE", "Finance / Accounting (read-only)"),
    ("CFO", "CFO (read-only, dashboards)"),
    ("EXECUTIVE", "Executive / Director (read-only)"),
    ("ADMIN", "System administrator"),
]

AUDIT_GUARD_FUNCTION = """
CREATE FUNCTION ppr_reject_audit_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only: % is not allowed', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("hosxp_source_id", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("department_source_id", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("hosxp_source_id", name=op.f("uq_app_user_hosxp_source_id")),
    )
    op.create_table(
        "hosxp_budget_category",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_source_id", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hosxp_budget_category")),
        sa.UniqueConstraint("source_id", name=op.f("uq_hosxp_budget_category_source_id")),
    )
    op.create_index(
        "ix_hosxp_budget_category_parent",
        "hosxp_budget_category",
        ["parent_source_id"],
        unique=False,
    )
    op.create_table(
        "hosxp_department",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hosxp_department")),
        sa.UniqueConstraint("source_id", name=op.f("uq_hosxp_department_source_id")),
    )
    op.create_table(
        "hosxp_fund_source",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hosxp_fund_source")),
        sa.UniqueConstraint("source_id", name=op.f("uq_hosxp_fund_source_source_id")),
    )
    op.create_table(
        "hosxp_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hosxp_item")),
        sa.UniqueConstraint("source_id", name=op.f("uq_hosxp_item_source_id")),
    )
    op.create_table(
        "role",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "code IN ('REQUESTER', 'PLAN_OFFICER', 'PROCUREMENT', 'HEAD_OF_PROCUREMENT', 'FINANCE', 'CFO', 'EXECUTIVE', 'ADMIN')",
            name=op.f("ck_role_known_code"),
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_role")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_kind", sa.Text(), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(actor_kind = 'USER' AND actor_user_id IS NOT NULL) OR (actor_kind = 'SYSTEM' AND actor_user_id IS NULL)",
            name=op.f("ck_audit_log_actor_consistent"),
        ),
        sa.CheckConstraint(
            "actor_kind IN ('USER', 'SYSTEM')", name=op.f("ck_audit_log_known_actor_kind")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["app_user.id"], name=op.f("fk_audit_log_actor_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "plan_year",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('DRAFT', 'APPROVED', 'ACTIVE', 'CLOSED')",
            name=op.f("ck_plan_year_known_state"),
        ),
        sa.CheckConstraint("ends_on > starts_on", name=op.f("ck_plan_year_range")),
        sa.CheckConstraint(
            "fiscal_year BETWEEN 1000 AND 9999", name=op.f("ck_plan_year_four_digit_year")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_plan_year_created_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_year")),
        sa.UniqueConstraint("fiscal_year", name=op.f("uq_plan_year_fiscal_year")),
    )
    op.create_table(
        "role_appointment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_code", sa.Text(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'ACTIVE'"), nullable=False),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role_code = 'HEAD_OF_PROCUREMENT'", name=op.f("ck_role_appointment_appointable_role")
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'REVOKED')", name=op.f("ck_role_appointment_known_status")
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_role_appointment_effective_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_role_appointment_created_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["role_code"], ["role.code"], name=op.f("fk_role_appointment_role_code_role")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_role_appointment_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_appointment")),
    )
    op.create_table(
        "sync_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("requested_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("records_checked", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_changed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_cancelled", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'RUNNING'"), nullable=False),
        sa.Column("error_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "mode <> 'MANUAL' OR requested_by_user_id IS NOT NULL",
            name=op.f("ck_sync_run_manual_has_requester"),
        ),
        sa.CheckConstraint("mode IN ('MANUAL', 'NIGHTLY')", name=op.f("ck_sync_run_known_mode")),
        sa.CheckConstraint(
            "status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')",
            name=op.f("ck_sync_run_known_status"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_sync_run_finish_after_start"),
        ),
        sa.CheckConstraint(
            "records_checked >= 0 AND records_created >= 0 AND records_updated >= 0 AND records_changed >= 0 AND records_cancelled >= 0",
            name=op.f("ck_sync_run_non_negative_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_sync_run_requested_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_run")),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_code", sa.Text(), nullable=False),
        sa.Column("granted_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_user_role_granted_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["role_code"], ["role.code"], name=op.f("fk_user_role_role_code_role")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_user_role_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("user_id", "role_code", name=op.f("pk_user_role")),
    )
    op.create_table(
        "sync_change",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sync_run_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("change_kind", sa.Text(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"], ["sync_run.id"], name=op.f("fk_sync_change_sync_run_id_sync_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_change")),
        sa.UniqueConstraint(
            "sync_run_id",
            "entity_type",
            "source_id",
            "change_kind",
            name=op.f("uq_sync_change_sync_run_id"),
        ),
    )
    op.create_index("ix_sync_change_run", "sync_change", ["sync_run_id"], unique=False)
    # ### end Alembic commands ###

    # --- Roles (spec §22). Codes are this system's authorization roles, not HOSxP data.
    role_table = sa.table("role", sa.column("code", sa.Text), sa.column("description", sa.Text))
    op.bulk_insert(role_table, [{"code": c, "description": d} for c, d in ROLES])

    # --- audit_log is append-only (spec §36): block UPDATE, DELETE and TRUNCATE.
    op.execute(AUDIT_GUARD_FUNCTION)
    op.execute(
        "CREATE TRIGGER audit_log_no_update_delete BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION ppr_reject_audit_mutation()"
    )
    op.execute(
        "CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log "
        "FOR EACH STATEMENT EXECUTE FUNCTION ppr_reject_audit_mutation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS ppr_reject_audit_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_change_run", table_name="sync_change")
    op.drop_table("sync_change")
    op.drop_table("user_role")
    op.drop_table("sync_run")
    op.drop_table("role_appointment")
    op.drop_table("plan_year")
    op.drop_index("ix_audit_log_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("role")
    op.drop_table("hosxp_item")
    op.drop_table("hosxp_fund_source")
    op.drop_table("hosxp_department")
    op.drop_index("ix_hosxp_budget_category_parent", table_name="hosxp_budget_category")
    op.drop_table("hosxp_budget_category")
    op.drop_table("app_user")
    # ### end Alembic commands ###
