"""Wave 2 Plan Core: plan_budget, plan_item, plan_item_demand, append-only plan_ledger.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

LEDGER_GUARD_FUNCTION = """
CREATE FUNCTION ppr_reject_ledger_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'plan_ledger is append-only: % is not allowed', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_budget",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_year_id", sa.BigInteger(), nullable=False),
        sa.Column("fund_source_source_id", sa.Text(), nullable=False),
        sa.Column("budget_category_source_id", sa.Text(), nullable=False),
        sa.Column("approved_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("approved_amount >= 0", name=op.f("ck_plan_budget_non_negative_amount")),
        sa.ForeignKeyConstraint(
            ["budget_category_source_id"],
            ["hosxp_budget_category.source_id"],
            name=op.f("fk_plan_budget_budget_category_source_id_hosxp_budget_category"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_plan_budget_created_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["fund_source_source_id"],
            ["hosxp_fund_source.source_id"],
            name=op.f("fk_plan_budget_fund_source_source_id_hosxp_fund_source"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_year_id"], ["plan_year.id"], name=op.f("fk_plan_budget_plan_year_id_plan_year")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_budget")),
        sa.UniqueConstraint("id", "plan_year_id", name="uq_plan_budget_id_year"),
        sa.UniqueConstraint(
            "plan_year_id",
            "fund_source_source_id",
            "budget_category_source_id",
            name="uq_plan_budget_line",
        ),
    )
    op.create_table(
        "plan_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_year_id", sa.BigInteger(), nullable=False),
        sa.Column("plan_budget_id", sa.BigInteger(), nullable=False),
        sa.Column("plan_type", sa.Text(), nullable=False),
        sa.Column("item_source_id", sa.Text(), nullable=False),
        sa.Column("item_code_snapshot", sa.Text(), nullable=False),
        sa.Column("item_name_snapshot", sa.Text(), nullable=False),
        sa.Column("unit_snapshot", sa.Text(), nullable=False),
        sa.Column("owner_department_source_id", sa.Text(), nullable=False),
        sa.Column("purchasing_department_source_id", sa.Text(), nullable=True),
        sa.Column("planned_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("estimated_unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("planned_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("q1", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("q2", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("q3", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("q4", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "plan_type IN ('DEPARTMENT', 'CENTRAL', 'ASSIGNED')",
            name=op.f("ck_plan_item_known_plan_type"),
        ),
        sa.CheckConstraint(
            "coalesce(q1, 0) >= 0 AND coalesce(q2, 0) >= 0 AND coalesce(q3, 0) >= 0 AND coalesce(q4, 0) >= 0",
            name=op.f("ck_plan_item_non_negative_quarters"),
        ),
        sa.CheckConstraint(
            "estimated_unit_price >= 0", name=op.f("ck_plan_item_non_negative_price")
        ),
        sa.CheckConstraint("planned_amount >= 0", name=op.f("ck_plan_item_non_negative_amount")),
        sa.CheckConstraint("planned_qty > 0", name=op.f("ck_plan_item_positive_qty")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_plan_item_created_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["item_source_id"],
            ["hosxp_item.source_id"],
            name=op.f("fk_plan_item_item_source_id_hosxp_item"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_department_source_id"],
            ["hosxp_department.source_id"],
            name=op.f("fk_plan_item_owner_department_source_id_hosxp_department"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_budget_id", "plan_year_id"],
            ["plan_budget.id", "plan_budget.plan_year_id"],
            name="fk_plan_item_budget_same_year",
        ),
        sa.ForeignKeyConstraint(
            ["purchasing_department_source_id"],
            ["hosxp_department.source_id"],
            name=op.f("fk_plan_item_purchasing_department_source_id_hosxp_department"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_item")),
    )
    op.create_index("ix_plan_item_owner", "plan_item", ["owner_department_source_id"], unique=False)
    op.create_index("ix_plan_item_year", "plan_item", ["plan_year_id"], unique=False)
    op.create_table(
        "plan_item_demand",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_item_id", sa.BigInteger(), nullable=False),
        sa.Column("department_source_id", sa.Text(), nullable=False),
        sa.Column("demand_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'PLANNED'"), nullable=False),
        sa.CheckConstraint(
            "state IN ('PLANNED', 'INCLUDED_IN_CENTRAL_PURCHASE', 'FULFILLED', 'CANCELLED')",
            name=op.f("ck_plan_item_demand_known_state"),
        ),
        sa.CheckConstraint("demand_qty > 0", name=op.f("ck_plan_item_demand_positive_qty")),
        sa.ForeignKeyConstraint(
            ["department_source_id"],
            ["hosxp_department.source_id"],
            name=op.f("fk_plan_item_demand_department_source_id_hosxp_department"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_item_id"],
            ["plan_item.id"],
            name=op.f("fk_plan_item_demand_plan_item_id_plan_item"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_item_demand")),
        sa.UniqueConstraint(
            "plan_item_id", "department_source_id", name="uq_plan_item_demand_dept"
        ),
    )
    op.create_table(
        "plan_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_item_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("qty_delta", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("amount_delta", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("ppr_ref", sa.Text(), nullable=True),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(event_type <> 'PLAN_APPROVED' OR (qty_delta >= 0 AND amount_delta >= 0)) AND (event_type <> 'PPR_CONFIRMED' OR (qty_delta < 0 AND amount_delta <= 0)) AND (event_type <> 'PPR_RELEASED' OR (qty_delta >= 0 AND amount_delta >= 0 AND (qty_delta > 0 OR amount_delta > 0))) AND (event_type <> 'PLAN_AMENDMENT' OR (qty_delta <> 0 OR amount_delta <> 0)) AND (event_type <> 'CENTRAL_STOCK_ISSUE' OR (qty_delta < 0 AND amount_delta = 0)) AND (event_type <> 'CENTRAL_STOCK_RETURN' OR (qty_delta > 0 AND amount_delta = 0))",
            name=op.f("ck_plan_ledger_event_signs"),
        ),
        sa.CheckConstraint(
            "event_type IN ('PLAN_APPROVED', 'PPR_CONFIRMED', 'PPR_RELEASED', 'PLAN_AMENDMENT', 'CENTRAL_STOCK_ISSUE', 'CENTRAL_STOCK_RETURN')",
            name=op.f("ck_plan_ledger_known_event"),
        ),
        sa.CheckConstraint(
            "event_type NOT IN ('PPR_CONFIRMED', 'PPR_RELEASED') OR ppr_ref IS NOT NULL",
            name=op.f("ck_plan_ledger_ppr_ref_required"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["app_user.id"], name=op.f("fk_plan_ledger_actor_user_id_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["plan_item_id"], ["plan_item.id"], name=op.f("fk_plan_ledger_plan_item_id_plan_item")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_ledger")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_plan_ledger_idempotency_key")),
    )
    op.create_index("ix_plan_ledger_item", "plan_ledger", ["plan_item_id"], unique=False)
    op.create_index(
        "uq_plan_ledger_one_approval",
        "plan_ledger",
        ["plan_item_id"],
        unique=True,
        postgresql_where=sa.text("event_type = 'PLAN_APPROVED'"),
    )
    # ### end Alembic commands ###

    # --- plan_ledger is append-only (spec §18.3, §30): block UPDATE, DELETE, TRUNCATE.
    op.execute(LEDGER_GUARD_FUNCTION)
    op.execute(
        "CREATE TRIGGER plan_ledger_no_update_delete BEFORE UPDATE OR DELETE ON plan_ledger "
        "FOR EACH ROW EXECUTE FUNCTION ppr_reject_ledger_mutation()"
    )
    op.execute(
        "CREATE TRIGGER plan_ledger_no_truncate BEFORE TRUNCATE ON plan_ledger "
        "FOR EACH STATEMENT EXECUTE FUNCTION ppr_reject_ledger_mutation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS plan_ledger_no_truncate ON plan_ledger")
    op.execute("DROP TRIGGER IF EXISTS plan_ledger_no_update_delete ON plan_ledger")
    op.execute("DROP FUNCTION IF EXISTS ppr_reject_ledger_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_plan_ledger_one_approval",
        table_name="plan_ledger",
        postgresql_where=sa.text("event_type = 'PLAN_APPROVED'"),
    )
    op.drop_index("ix_plan_ledger_item", table_name="plan_ledger")
    op.drop_table("plan_ledger")
    op.drop_table("plan_item_demand")
    op.drop_index("ix_plan_item_year", table_name="plan_item")
    op.drop_index("ix_plan_item_owner", table_name="plan_item")
    op.drop_table("plan_item")
    op.drop_table("plan_budget")
    # ### end Alembic commands ###
