"""Wave 4 PPR core: ppr, lifetime PR binding, items, allocation, versions, sequence.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29

* ``ppr_binding.pr_no`` is the primary key: a PR number binds to at most one confirmed
  PPR, for life, unconditionally (D-03). A trigger forbids UPDATE/DELETE/TRUNCATE, so
  the binding survives cancellation.
* ``uq_ppr_one_working_draft``: at most one working draft per PR (D-05).
* ``ppr_version`` rows are confirmation evidence (§15.3, §35) and append-only (trigger).
* ``ppr_sequence``: per-fiscal-year PPR numbers (D-06).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EVIDENCE_GUARD_FUNCTION = """
CREATE FUNCTION ppr_reject_evidence_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$
"""
GUARDED = ("ppr_version", "ppr_binding")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ppr_sequence",
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.CheckConstraint("last_value BETWEEN 0 AND 999999", name=op.f("ck_ppr_sequence_range")),
        sa.PrimaryKeyConstraint("fiscal_year", name=op.f("pk_ppr_sequence")),
    )
    op.create_table(
        "ppr",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("pr_no", sa.Text(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("department_source_id", sa.Text(), nullable=False),
        sa.Column("fund_source_source_id", sa.Text(), nullable=False),
        sa.Column("pr_budget_category_source_id", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column("ppr_number", sa.Text(), nullable=True),
        sa.Column("current_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("required_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("adjustment_reference", sa.Text(), nullable=True),
        sa.Column("hosxp_pr_status", sa.Text(), nullable=False),
        sa.Column("hosxp_native_status", sa.Text(), nullable=True),
        sa.Column("draft_pr", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("discarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(state = 'DRAFT') = (ppr_number IS NULL)", name=op.f("ck_ppr_number_iff_confirmed")
        ),
        sa.CheckConstraint(
            "discarded_at IS NULL OR state = 'DRAFT'", name=op.f("ck_ppr_only_drafts_discarded")
        ),
        sa.CheckConstraint(
            "state IN ('DRAFT', 'CONFIRMED_LOCKED', 'PROCUREMENT_VERIFIED', 'PR_CHANGED_REVIEW_REQUIRED', 'UNLOCKED_FOR_REVISION', 'CANCELLED', 'CLOSED')",
            name=op.f("ck_ppr_known_state"),
        ),
        sa.CheckConstraint("current_version >= 0", name=op.f("ck_ppr_version_non_negative")),
        sa.CheckConstraint("required_amount >= 0", name=op.f("ck_ppr_non_negative_amount")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["app_user.id"], name=op.f("fk_ppr_created_by_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ppr")),
        sa.UniqueConstraint("ppr_number", name=op.f("uq_ppr_ppr_number")),
    )
    op.create_index("ix_ppr_department", "ppr", ["department_source_id"], unique=False)
    op.create_index(
        "uq_ppr_one_working_draft",
        "ppr",
        ["pr_no"],
        unique=True,
        postgresql_where=sa.text("state = 'DRAFT' AND discarded_at IS NULL"),
    )
    op.create_table(
        "ppr_binding",
        sa.Column("pr_no", sa.Text(), nullable=False),
        sa.Column("ppr_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "bound_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["ppr_id"], ["ppr.id"], name=op.f("fk_ppr_binding_ppr_id_ppr")),
        sa.PrimaryKeyConstraint("pr_no", name=op.f("pk_ppr_binding")),
        sa.UniqueConstraint("ppr_id", name=op.f("uq_ppr_binding_ppr_id")),
    )
    op.create_table(
        "ppr_category_allocation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ppr_id", sa.BigInteger(), nullable=False),
        sa.Column("budget_category_source_id", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_ppr_category_allocation_positive_amount")),
        sa.ForeignKeyConstraint(
            ["ppr_id"],
            ["ppr.id"],
            name=op.f("fk_ppr_category_allocation_ppr_id_ppr"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ppr_category_allocation")),
        sa.UniqueConstraint(
            "ppr_id", "budget_category_source_id", name="uq_ppr_allocation_category"
        ),
    )
    op.create_table(
        "ppr_version",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ppr_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("document_code", sa.Text(), nullable=False),
        sa.Column("confirmed_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_ppr_version_positive_version")),
        sa.ForeignKeyConstraint(
            ["confirmed_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_ppr_version_confirmed_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(["ppr_id"], ["ppr.id"], name=op.f("fk_ppr_version_ppr_id_ppr")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ppr_version")),
        sa.UniqueConstraint("document_code", name=op.f("uq_ppr_version_document_code")),
        sa.UniqueConstraint("ppr_id", "version", name="uq_ppr_version_number"),
    )
    op.create_table(
        "ppr_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ppr_id", sa.BigInteger(), nullable=False),
        sa.Column("pr_item_id", sa.Text(), nullable=False),
        sa.Column("item_source_id", sa.Text(), nullable=False),
        sa.Column("item_name", sa.Text(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("plan_item_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_ppr_item_non_negative_amount")),
        sa.CheckConstraint("qty > 0", name=op.f("ck_ppr_item_positive_qty")),
        sa.ForeignKeyConstraint(
            ["plan_item_id"], ["plan_item.id"], name=op.f("fk_ppr_item_plan_item_id_plan_item")
        ),
        sa.ForeignKeyConstraint(
            ["ppr_id"], ["ppr.id"], name=op.f("fk_ppr_item_ppr_id_ppr"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ppr_item")),
        sa.UniqueConstraint("ppr_id", "pr_item_id", name="uq_ppr_item_line"),
    )
    op.create_index("ix_ppr_item_ppr", "ppr_item", ["ppr_id"], unique=False)
    # ### end Alembic commands ###
    op.execute(EVIDENCE_GUARD_FUNCTION)
    for table in GUARDED:
        op.execute(
            f"CREATE TRIGGER {table}_no_update_delete BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION ppr_reject_evidence_mutation()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION ppr_reject_evidence_mutation()"
        )


def downgrade() -> None:
    for table in GUARDED:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_update_delete ON {table}")
    op.execute("DROP FUNCTION IF EXISTS ppr_reject_evidence_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ppr_item_ppr", table_name="ppr_item")
    op.drop_table("ppr_item")
    op.drop_table("ppr_version")
    op.drop_table("ppr_category_allocation")
    op.drop_table("ppr_binding")
    op.drop_index(
        "uq_ppr_one_working_draft",
        table_name="ppr",
        postgresql_where=sa.text("state = 'DRAFT' AND discarded_at IS NULL"),
    )
    op.drop_index("ix_ppr_department", table_name="ppr")
    op.drop_table("ppr")
    op.drop_table("ppr_sequence")
    # ### end Alembic commands ###
